### ISSUE TITLE
很实用的一个插件, 提高了我的办公效率

### ISSUE THREAD

**Issue by zuilintan** [MrDenua/WiFiADB#1]
建议增加每个项的备注功能, 公司的每台车机Model_Name都相同, 
或者优化列宽度自适应, 现在每次打开, 列表项都会缩在一起, 区分各项需要再拉伸一下

**Comment by MrDenua** [comment]
感谢建议, 
- 我将在下一次更新中考虑添加备注功能,
- 列宽为窗口宽度/列数, 不知你那是显示异常还是其他什么

**Comment by zuilintan** [comment]
![image](https://user-images.githubusercontent.com/34953840/69389953-8924a100-0d08-11ea-9492-0ac39ce20d4e.png)
类似这里, 可以实现自适应列内容大小吗?

**Comment by MrDenua** [comment]
自适应其他的列就展示不完全了, 我后面会添加记忆当前列宽 或 可以选择显示哪些列

**Comment by zuilintan** [comment]
![image](https://user-images.githubusercontent.com/34953840/69390022-cf7a0000-0d08-11ea-9bf5-52a97d154bac.png)
然后这里存在个问题, 点击CONNECT, 连接成功后, DISCONNECT被旧内容遮挡

**Comment by MrDenua** [comment]
这个问题我也发现了, 由于这是我第一次使用Swing, 所以没做好

**Comment by MrDenua** [comment]
新版本正在审核中, 以上问题均已修复
