### ISSUE TITLE
【MacOs】CmdUtils.execSync: Cannot run program "adb": error=2, No such file or directory

### ISSUE THREAD

**Issue by dvc890** [MrDenua/WiFiADB#3]
在终端可以使用adb命令，环境配置没有问题，但是在androidstudio使用这个插件就不行，CmdUtils.execSync: Cannot run program "adb": error=2, No such file or directory

**Comment by itm-mic** [comment]
I got the same problem. I can run this command in android studio terminal without problems. The command will be run also in iTerm2 without errors. 
The environment variable PATH contains also the necessary directories. This path will be set in file .bash_profile. 
What is missing on my system?

![Bildschirmfoto 2019-12-04 um 15 35 18](https://user-images.githubusercontent.com/23215979/70154634-22f93000-16b1-11ea-8e22-c46faa07625f.png)

**Comment by MrDenua** [comment]
@dvc890  
感谢提出问题, 这个问题我已在最新的  [Release](https://github.com/MrDenua/WiFiADB/releases) 中尝试修复. 

@itm-mic 
Thanks for your issue, I have tried to fix this bug at  [Latest Release](https://github.com/MrDenua/WiFiADB/releases).

**Comment by dvc890** [comment]
> @dvc890
> 感谢提出问题, 这个问题我已在最新的 [Release](https://github.com/MrDenua/WiFiADB/releases) 中尝试修复.
> 
> @itm-mic
> Thanks for your issue, I have tried to fix this bug at [Latest Release](https://github.com/MrDenua/WiFiADB/releases).

CmdUtils.execSync: Cannot run program "devices": error=2, No such file or directory
谢谢@MrDenua的修复，不过又出现新的问题

**Comment by MrDenua** [comment]
@dvc890 
这个有点尴尬了, 
请问你有用 zsh 之类的吗, 在 bash 中使用 adb 是正常的吗
能把详细的 log 贴出来我参考参考吗

**Comment by dvc890** [comment]
> @dvc890
> 这个有点尴尬了,
> 请问你有用 zsh 之类的吗, 在 bash 中使用 adb 是正常的吗
> 能把详细的 log 贴出来我参考参考吗

用zsh也正常

**Comment by MrDenua** [comment]
@dvc890 
这个问题有点棘手, 目前解决的办法是手动配置 adb path, 最新的 [release ](https://github.com/MrDenua/WiFiADB/releases) 中已添加该功能

@itm-mic 
The solution now is  configure adb path in plugin. the
 [Latest Release](https://github.com/MrDenua/WiFiADB/releases) has implemented this feature

**Comment by itm-mic** [comment]
Thx for bugfixing. The new version works very well.
