### ISSUE TITLE
华为P30 Pro系统android10.0 未适配

### ISSUE THREAD

**Issue by Roc-egg** [MrDenua/WiFiADB#4]
华为P30 Pro系统android10.0 未适配，点击connect连接失败log提示没有权限，10.0以下的可以连接

**Comment by MrDenua** [comment]
感谢提议, 这是一个已知问题, 我尽快将在下一个版本兼容 Android10.

**Comment by MrDenua** [comment]
最新的 [Release](https://github.com/MrDenua/WiFiADB/releases) 已兼容 Android 10
更新已提交到 jetbrains plugin repository
